# https://taskfile.dev

version: "3"

output: "prefixed"
# output:
#   group:
#     begin: "[{{.TASK}}]"
#     end: ""

vars:
  GIT_WORKSPACE: /home/test/repositories
  PROJECTS_FILE: projects.yml
  REPO_NAMES:
    sh: yq '.repos.[].name' < "{{.PROJECTS_FILE}}"

tasks:
  default:
    cmds:
      - for: { var: REPO_NAMES }
        cmd: echo "{{.ITEM}}"

  repos:
    cmds:
      - for: { var: REPO_NAMES }
        cmd: echo "{{.ITEM}}"

  paths:
    vars:
      REPO_PATHS:
        sh: yq '.repos.[].path' < "{{.PROJECTS_FILE}}"
    cmds:
      - for: { var: REPO_PATHS }
        cmd: echo "{{joinPath .GIT_WORKSPACE .ITEM}}"

  git-script:
    vars:
      REPO_NAME: '{{default "" .REPO_NAME}}'
    cmds:
      - bin/git.sh --config "{{.PROJECTS_FILE}}" --workspace "{{.GIT_WORKSPACE}}" --name "{{.REPO_NAME}}" {{.CLI_ARGS}}
    prefix: "bin/git.sh --name {{.REPO_NAME}} {{.CLI_ARGS}}"

  git:
    cmds:
      - for: { var: REPO_NAMES }
        task: git-script
        vars:
          REPO_NAME: "{{.ITEM}}"
