vars:
  - name: boolvar
    bool: true
  - name: intvar
    int: 42
  - name: floatvar
    float: 3.14
  - name: stringvar
    string: "some text"
  - name: shellvar
    shell: "id -u | tr -d '\n'"
  - name: home
    env: HOME
  - name: filevar
    file: "{{.home}}/.gitconfig"
  - name: jsonvar
    json: '{"foo": "bar"}'
  - name: yamlvar
    yaml: |
      foo: bar
      baz: qux
      val: 42
  - name: yamlvar2
    yaml: 'foo: bar'
  - name: user
    shell: "whoami | tr -d '\n'"
  - name: upper
    shell: "echo {{.stringvar}} | tr '[:lower:]' '[:upper:]' | tr -d '\n'"
  - name: var1
    eval: "10"
  - name: var2
    eval: "23 + {{.var1}}"
  - name: bool1
    eval: "{{.var1}} > 30"
  - name: bool2
    eval: "{{.bool1}} && {{.var1}} < 50"
  - name: var3
    eval: "{{.yamlvar.val}} + 1"
