require-group: false

logging:
  color: true
  timestamps: true
  verbose: false
  commands: true
  duration: true
  duration-color: cyan
  begin: true
  begin-color: cyan
  command-color: yellow
  stdout-color: green
  stderr-color: red
  stdout-prefix: ""
  stderr-prefix: ""
  stderr-redirect: true

commands:
  - name: status
    description: "Show the working tree status"
    command: "git status"
    group:
      - all
  - name: log
    description: "Show the commit logs"
    command: "git log"
    group:
      - all
  - name: fetch
    description: "Fetch from the remote repository"
    command: "git fetch"
    group:
      - all
  - name: pull
    description: "Pull from the remote repository"
    command: "git pull"
    group:
      - all
  - name: push
    description: "Push to the remote repository"
    command: "git push"
    group:
      - all
  - name: newest
    description: "Show the newest commit"
    command: "git log -1"
    group:
      - all
  - name: newest-tag
    description: "Show the newest tag"
    command: "git tag --sort=-v:refname | head -n 1"
    group:
      - all

repos:
  - name: repo1
    url: git@gitbucket:/test/repo1.git
    path: /home/test/repositories/repo1
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - gitbucket
      - nolfs
      - first
  - name: repo2
    url: git@gitbucket:/test/repo2.git
    path: /home/test/repositories/repo2
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - gitbucket
      - nolfs
  - name: repo3
    url: git@gitbucket:/test/repo3.git
    path: /home/test/repositories/repo3
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - gitbucket
      - nolfs
  - name: repo4
    url: git@gitbucket:/test/repo4.git
    path: /home/test/repositories/repo4
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - gitbucket
      - nolfs
  - name: repo5
    url: git@gitbucket:/test/repo5.git
    path: /home/test/repositories/repo5
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - gitbucket
      - nolfs

  - name: repo6
    url: git@gitbucket:/test/repo6.git
    path: /home/test/repositories/repo6
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - gitbucket
      - lfs
  - name: repo7
    url: git@gitbucket:/test/repo7.git
    path: /home/test/repositories/repo7
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - gitbucket
      - lfs
  - name: repo8
    url: git@gitbucket:/test/repo8.git
    path: /home/test/repositories/repo8
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - gitbucket
      - lfs
  - name: repo9
    url: git@gitbucket:/test/repo9.git
    path: /home/test/repositories/repo9
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - gitbucket
      - lfs
  - name: repo10
    url: git@gitbucket:/test/repo10.git
    path: /home/test/repositories/repo10
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - gitbucket
      - lfs
      - last
  - name: icecream1
    url: git@softserve:/icecream1.git
    path: /home/test/repositories/icecream1
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - softserve
      - nolfs
      - first
  - name: icecream2
    url: git@softserve:/icecream2.git
    path: /home/test/repositories/icecream2
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - softserve
      - nolfs
  - name: icecream3
    url: git@softserve:/icecream3.git
    path: /home/test/repositories/icecream3
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - softserve
      - nolfs
  - name: icecream4
    url: git@softserve:/icecream4.git
    path: /home/test/repositories/icecream4
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - softserve
      - nolfs
  - name: icecream5
    url: git@softserve:/icecream5.git
    path: /home/test/repositories/icecream5
    uses-lfs: no
    uses-submodules: no
    group:
      - all
      - softserve
      - nolfs

  - name: icecream6
    url: git@softserve:/icecream6.git
    path: /home/test/repositories/icecream6
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - softserve
      - lfs
  - name: icecream7
    url: git@softserve:/icecream7.git
    path: /home/test/repositories/icecream7
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - softserve
      - lfs
  - name: icecream8
    url: git@softserve:/icecream8.git
    path: /home/test/repositories/icecream8
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - softserve
      - lfs
  - name: icecream9
    url: git@softserve:/icecream9.git
    path: /home/test/repositories/icecream9
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - softserve
      - lfs
  - name: icecream10
    url: git@softserve:/icecream10.git
    path: /home/test/repositories/icecream10
    uses-lfs: yes
    uses-submodules: no
    group:
      - all
      - softserve
      - lfs
      - last
